version: 0.0
os: linux
files:
  - source: /
    destination: /srv/app
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
